**OpenAI Gym: Carpole simple example (random actions)**

In [1]:
import gymnasium as gym

1- Create the environment and test it

In [2]:
env = gym.make("CartPole-v1")
obs = env.reset()
obs

(array([ 0.00513019,  0.02789485, -0.03485167,  0.04293759], dtype=float32),
 {})

2- Explore Action space

In [3]:
env.action_space # Possible actions: 0 (left), 1 (right)

Discrete(2)

3- Explore Observation space

In [4]:
env.observation_space # Obsrvation: [x, x', theta, theta']

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)

4- Push platform to the left

In [5]:
env.step(0)

(array([ 0.00568808, -0.16671045, -0.03399291,  0.32442397], dtype=float32),
 1.0,
 False,
 False,
 {})

5- Sample random action

In [6]:
env.action_space.sample()

np.int64(0)

6- Sample random observation

In [7]:
env.observation_space.sample()

array([-0.4519094 , -0.8045176 ,  0.08220743,  0.55225396], dtype=float32)

7- Implement a loop with random actions

In [20]:
total_reward = 0.0
total_steps = 0
obs = env.reset()

while True:
    action = env.action_space.sample() # take a random action
    tupla = env.step(action) # execute one step
    total_reward += tupla[1]
    total_steps += 1
    if tupla[2]:
        break

print("Episode done in %d steps, total reward %.2f" % (
    total_steps, total_reward))


Episode done in 13 steps, total reward 13.00
